name: Sean-Holt
favicon: null
layout_spectrum: 0.28756249719299376
typography_spectrum: 0.6671018197666854
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefeff'
    - '#2c2d27'
    - '#9bae07'
    - '#4483f7'
    - '#c54a4c'
  brandStrength: 0.5
  lightness: 0.9938129822257906
  saturation: 0.07080440409481525
  rhythmicContrast: 0.01978649036027491
purpose: []
